version: '3.8'

services:
  mongo1:
    image: candis/mongo-replica-set
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: localdb
    volumes:
      - "mongo1_data:/data/db"
    restart: always

volumes:
  mongo1_data: